repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.20.0
    hooks:
    -   id: validate_manifest
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--"]
    -   id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
    -   id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
